In [7]:
import numpy as np
from matplotlib import pyplot as plt

In [8]:
k_CH = 592
k_CC = 1580

# masa w amu
m_H = 1
m_C = 12
# amu = 1.6605*1e-27

N = 4
D = np.zeros((N,N))
IT = 200

D[1][1] = D[2][2] = (k_CC + k_CH) / m_C
D[0][0] = D[3][3] = k_CH / m_H
D[0][1] = D[3][2] = - k_CH / m_H
D[1][0] = D[2][3] = - k_CH / m_C
D[2][1] = D[1][2] = - k_CC / m_C

print(np.round(D, decimals=2))

[[ 592.   -592.      0.      0.  ]
 [ -49.33  181.   -131.67    0.  ]
 [   0.   -131.67  181.    -49.33]
 [   0.      0.   -592.    592.  ]]


### D = QR
### Q – macierz ortogonalna (Q T Q = I)
### R – macierz trójkątna górna.

In [10]:
I = np.zeros((N,N))
for i in range(0,N):
    for j in range(0,N):
        if i == j:
            I[i][i] = 1
R = D
Q = I

for _ in range(0, IT):
    for i in range(N-1): # 0,1,2
        x = R[:,i]
        j = 0 
        while j < i:
            x[j] = 0
            j += 1
        e = np.zeros(N)
        e[i] = 1
        u = x - np.dot(np.linalg.norm(x), e)
        v = u / np.linalg.norm(u)
        Q_t = I - np.dot(2, np.outer(v, v))
        Q = np.dot(Q_t, Q)
        R = np.dot(Q_t, R)

In [18]:
print(np.round(R, 2))

[[ 594.05    0.      0.      0.  ]
 [   0.    185.88    0.     34.94]
 [   0.      0.    593.02 -593.02]
 [   0.      0.      0.     -0.  ]]


In [22]:
print(np.round(np.transpose(Q), 2))

[[ 1.    0.06  0.    0.06]
 [-0.08  0.7   0.04  0.7 ]
 [ 0.   -0.71  0.04  0.7 ]
 [ 0.   -0.   -1.    0.06]]


In [23]:
print(np.round(np.dot(Q, R), 2))

[[ 592.    -15.44    0.     -2.9 ]
 [  34.82  130.76 -420.06  444.64]
 [   2.05    7.71   24.58  -23.13]
 [  34.88  130.99  417.88 -393.26]]
