# Basic modules

1. `numpy`: is a Python package for scientific computing. Provides multidimensional array objects and fast operations in arrays: [numpy](https://numpy.org/doc/stable/index.html)

2. `Matplotlib`: is a Python 2D plotting library which produces publication quality figures in a variety of hardcopy formats and interactive environments across platforms: [matplotlib](http://matplotlib.org/index.html)

# Python basics

In [1]:
print('Hi on 1st class!')

Hi on 1st class!


Variables

In [2]:
name = 'Anna'
number = 1
course = 'image processing'

text = f'Hi {name}, it\'s {number}st {course} class!'
print(text)

Hi Anna, it's 1st image processing class!


Numbers and basic mathematical operations

In [8]:
n1 = 643
n2 = 24

add_1 = n1 + n2
print('result of addition', add_1)

sub_1 = n1 - n2
print('result of subtraction', sub_1)

multi_1 = n1 * n2
print('result of multiplication', multi_1)

divi_1 = n1 / n2
print('result of division', divi_1)

result of addition 667
result of subtraction 619
result of multiplication 15432
result of division 26.791666666666668


# `numpy` basics

In [4]:
# import modules
import numpy as np

Mathematical operations by `numpy`

In [9]:
add_2 = np.add(n1, n2)
print('result of numpy addition', add_2)

sub_2 = np.subtract(n1, n2)
print('result of numpy subtraction', sub_2)

multi_2 = np.multiply(n1, n2)
print('result of numpy multiplication', multi_2)

divi_2 = np.divide(n1, n2)
print('result of numpy division', divi_2)

result of numpy addition 667
result of numpy subtraction 619
result of numpy multiplication 15432
result of numpy division 26.791666666666668


Creating 2-dimensional `numpy` array  

In [10]:
ar1 = np.array([[1,2,3,4], [11,12,13,14], [21,22,23,24]])
print(ar1)

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]


  > function `np.arange(start, stop, step)`   
  > where `step = 1` - default

In [20]:
ar2 = np.arange(4*4).reshape(4,4)
print(ar2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [24]:
ar3 = np.arange(1,35,3).reshape(3,4)
print(ar3)

[[ 1  4  7 10]
 [13 16 19 22]
 [25 28 31 34]]


> function `np.random.randint(start,stop,shape)`

In [36]:
ar4 = np.random.randint(0,100, (4,4))
print(ar4)


[[28  1 17 51]
 [57 62 10 25]
 [79 66 64 60]
 [96  0 44 94]]


`Exercise:`
- `Create two numpay arrays (eg. 5x5) and make basic mathematical operations` 
- `Find (in the documnetation) and use 3 other numpy mathematical methods`
- `Try with two arrays with different sizes - what happend?`

In [33]:
array1 = np.random.randint(0,100, (4,4))
array2 = np.random.randint(0,50, (4,4))
print(array1)
print(array2)

[[70 31 29 31]
 [66 98 55 46]
 [90 79 99 55]
 [73 34 52 62]]
[[32  6  8 13]
 [35 19 42 45]
 [12 22 31 44]
 [27  5 31 19]]


In [34]:
add_1_ar = np.add(array1, array2)
print(add_1_ar)

[[102  37  37  44]
 [101 117  97  91]
 [102 101 130  99]
 [100  39  83  81]]


`numpy` array creating function

In [5]:
np.eye(4)
np.eye(4,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [13]:
np.diag([2,4,5,6])

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [15]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

array's characteristics

In [55]:
arr = np.random.randint(1,78, (3,4))
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(type(arr))
print(arr.min(), arr.max())
print(arr.min(axis=0))
print(arr.sum())


[[77 34 67 19]
 [67 38 18  3]
 [12 63 65 32]]
(3, 4)
2
12
int64
<class 'numpy.ndarray'>
3 77
[12 34 18  3]
495


# `numpy` array indexing

## By index

Selecting array elements by specifying indexes:
   
   - selection principle:
     - first, indexes of rows are given, then indexes of columns
     - indexes are given by: [start, stop, step, start, stop, step]
   - examples of row and column selection:

In [7]:
x = np.arange(3*6).reshape(3,6)
print(f'x.shape (rows,cols): {x.shape},\n\nx:\n{x}')

x.shape (rows,cols): (3, 6),

x:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [10]:
# select all rows (':' character) and all columns (':' character)
print(f'1. All rows and all columns:\n{x[:,:]}\n')

# select first row (index 0) and all columns (the sign ':')
print(f'2. First row and all columns:\n{x[0,:]}\n')

#select the last two rows and the last two columns
print(f'3. The last two rows and the last two columns:\n{x[1:,4:]}\n\nor:')

# or
print(x[-2:,-2:],'\n')

1. All rows and all columns:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

2. First row and all columns:
[0 1 2 3 4 5]

3. The last two rows and the last two columns:
[[10 11]
 [16 17]]

or:
[[10 11]
 [16 17]] 



In [46]:
# select every second row and every third column
print(x[0:3:2,0:6:3],'\n') 

# or
print(x[::2,::3],'\n') 

[[ 0  3]
 [12 15]] 

[[ 0  3]
 [12 15]] 



## By conditions
Selecting items by logical conditions

In [47]:
s ='select items larger than 10'
print(s,x[x>10],'\n',sep='\n')

s = 'select items larger than 8 and smaller than 15'
print(s,x[(x>8) & (x<15)],sep='\n')

select items larger than 10
[11 12 13 14 15 16 17]


select items larger than 8 and smaller than 15
[ 9 10 11 12 13 14]


## New values

Assigning new values to array cells selected based on a logical condition


In [48]:
s1 = 'Replace less than 6 with 99'
x1 = x.copy()
x1[x<6] = 99

s2 = 'Replace larger than 9 and smaller than 15 with 1000'
x2 = x.copy()
x2[(x2>9) & (x2<15)] = 100

print(f'oryginal:\n{x}\n\n{s1}:\n{x1}\n\n{s2}\n{x2}')

oryginal:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

Replace less than 6 with 99:
[[99 99 99 99 99 99]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]

Replace larger than 9 and smaller than 15 with 1000
[[  0   1   2   3   4   5]
 [  6   7   8   9 100 100]
 [100 100 100  15  16  17]]
