# Basic modules

1. `numpy`: is a Python package for scientific computing. Provides multidimensional array objects and fast operations in arrays: [numpy](https://numpy.org/doc/stable/index.html)

2. `Matplotlib`: is a Python 2D plotting library which produces publication quality figures in a variety of hardcopy formats and interactive environments across platforms: [matplotlib](http://matplotlib.org/index.html)

# Python basics

In [1]:
print()

Hi on 1st class!


Variables

In [2]:
name = 
number = 
course = 

text = 
print(text)

Hi Anna, it's 1st image processing class!


Numbers and basic mathematical operations

In [8]:
n1 = 
n2 = 



result of addition 667
result of subtraction 619
result of multiplication 15432
result of division 26.791666666666668


# `numpy` basics

In [4]:
# import modules
import numpy as np

Mathematical operations by `numpy`

result of numpy addition 667
result of numpy subtraction 619
result of numpy multiplication 15432
result of numpy division 26.791666666666668


Creating 2-dimensional `numpy` array  

In [10]:
ar1 = 
print(ar1)

[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]]


  > function `np.arange(start, stop, step)`   
  > where `step = 1` - default

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


[[ 1  4  7 10]
 [13 16 19 22]
 [25 28 31 34]]


> function `np.random.randint(start,stop,shape)`

In [36]:
ar4 = np.random.randint(0,100, (4,4))
print(ar4)


[[28  1 17 51]
 [57 62 10 25]
 [79 66 64 60]
 [96  0 44 94]]


`Exercise:`
- `Create two numpay arrays (eg. 5x5) and make basic mathematical operations` 
- `Find (in the documnetation) and use 3 other numpy mathematical methods`
- `Try with two arrays with different sizes - what happend?`

`numpy` array creating function

In [5]:
np.eye(4)
np.eye(4,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [13]:
np.diag([2,4,5,6])

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [15]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

array's characteristics
print: shape, size, type, min, max ...

# `numpy` array indexing

## By index

Selecting array elements by specifying indexes:
   
   - selection principle:
     - first, indexes of rows are given, then indexes of columns
     - indexes are given by: [start, stop, step, start, stop, step]
   - examples of row and column selection:

In [7]:
x = np.arange(3*6).reshape(3,6)
print(f'x.shape (rows,cols): {x.shape},\n\nx:\n{x}')

x.shape (rows,cols): (3, 6),

x:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [3]:
# select all rows (':' character) and all columns (':' character)
print(f'1. All rows and all columns:\n{}\n')

# select first row (index 0) and all columns (the sign ':')
print(f'2. First row and all columns:\n{}\n')

#select the last two rows and the last two columns
print(f'3. The last two rows and the last two columns:\n{}\n\nor:')

# or
print( ,'\n')

SyntaxError: f-string: empty expression not allowed (2354800087.py, line 2)

In [6]:
# select every second row and every third column
print(x[],'\n') 

# or
print(x[],'\n') 

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1263534306.py, line 2)

## By conditions
Selecting items by logical conditions

In [4]:
s ='select items larger than 10'


s = 'select items larger than 8 and smaller than 15'


## New values

Assigning new values to array cells selected based on a logical condition


In [7]:
s1 = 'Replace less than 6 with 99'


s2 = 'Replace larger than 9 and smaller than 15 with 1000'


print()