In [8]:
import numpy as np

In [21]:
def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n, n))
    U = np.zeros((n, n))
    
    for i in range(n):
        for k in range(i, n):
            U[i][k] = A[i][k] - sum(L[i][j] * U[j][k] for j in range(i))
        
        for k in range(i, n):
            if i == k:
                L[i][i] = 1
            else:
                L[k][i] = (A[k][i] - sum(L[k][j] * U[j][i] for j in range(i))) / U[i][i]
    
    return L, U

def generate_matrix(n):
    A = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            A[i][j] = 1 / (i + j + 2)
    return A

# Funkcja do ekstrakcji elementów diagonalnych z macierzy U
def extract_diagonal(U):
    n = len(U)
    diagonal = [U[i][i] for i in range(n)]
    return diagonal

# Funkcja do obliczenia wyznacznika macierzy A
def calculate_determinant(U):
    return np.prod(extract_diagonal(U))

In [22]:
# Test
n = 4
A = generate_matrix(n)
print("Wygenerowana macierz A:")
print(A)

L, U = lu_decomposition(A)
print("Matrix L:")
print(L)
print("Matrix U:")
print(U)

Wygenerowana macierz A:
[[0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]
 [0.2        0.16666667 0.14285714 0.125     ]]
Matrix L:
[[1.         0.         0.         0.        ]
 [0.66666667 1.         0.         0.        ]
 [0.5        1.2        1.         0.        ]
 [0.4        1.2        1.71428571 1.        ]]
Matrix U:
[[5.00000000e-01 3.33333333e-01 2.50000000e-01 2.00000000e-01]
 [0.00000000e+00 2.77777778e-02 3.33333333e-02 3.33333333e-02]
 [0.00000000e+00 0.00000000e+00 1.66666667e-03 2.85714286e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.02040816e-04]]


In [23]:
print("Elementy diagonalne macierzy U:")
print(extract_diagonal(U))

print("\nWyznacznik macierzy A:", calculate_determinant(U))

Elementy diagonalne macierzy U:
[0.5, 0.02777777777777779, 0.0016666666666666219, 0.0001020408163264902]

Wyznacznik macierzy A: 2.3620559334835072e-09


In [24]:
def solve_systems(L, U, bs):
    n = len(L)
    x_solutions = []
    for b in bs:
        # Rozwiązanie układu równań Ly = b
        y = np.linalg.solve(L, b)
        # Rozwiązanie układu równań Ux = y
        x = np.linalg.solve(U, y)
        x_solutions.append(x)
    return np.column_stack(x_solutions)  # Złożenie rozwiązań w macierz kolumnową

In [25]:


# Wektory wyrazów wolnych
bs = [np.array([1, 0, 0, 0]),
      np.array([0, 1, 0, 0]),
      np.array([0, 0, 1, 0]),
      np.array([0, 0, 0, 1])]

# Rozkład LU
L, U = lu_decomposition(A)

A_inv = solve_systems(L, U, bs)

print("Macierz odwrotna A^-1:")
print(A)
print(A_inv)

Macierz odwrotna A^-1:
[[0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]
 [0.2        0.16666667 0.14285714 0.125     ]]
[[   200.          -1200.           2100.          -1120.        ]
 [ -1200.           8100.         -15120.00000001   8400.        ]
 [  2100.         -15120.00000001  29400.00000001 -16800.00000001]
 [ -1120.           8400.         -16800.00000001   9800.        ]]


In [26]:
L, U = lu_decomposition(A)

# Obliczenie iloczynu A * A^-1
A_inv = solve_systems(L, U, [np.eye(n)] * n)  # Tworzymy listę macierzy jednostkowych o rozmiarze n
C = np.dot(A, A_inv)

print("Iloczyn macierzy A i A^-1:")
print(C)

# Obliczenie iloczynu C = A * B
B = np.eye(n)  # Będziemy używać macierzy jednostkowej B
C = np.zeros((n, n))

# Obliczanie elementów macierzy C
for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i][j] += A[i][k] * B[k][j]

print("\nMacierz C = A * B:")
print(C)

Iloczyn macierzy A i A^-1:
[[ 1.00000000e+00  1.84208204e-13  8.63309424e-14 -2.54996024e-13
   1.00000000e+00  1.84208204e-13  8.63309424e-14 -2.54996024e-13
   1.00000000e+00  1.84208204e-13  8.63309424e-14 -2.54996024e-13
   1.00000000e+00  1.84208204e-13  8.63309424e-14 -2.54996024e-13]
 [-2.75335310e-14  1.00000000e+00 -1.47733677e-13  6.09142366e-14
  -2.75335310e-14  1.00000000e+00 -1.47733677e-13  6.09142366e-14
  -2.75335310e-14  1.00000000e+00 -1.47733677e-13  6.09142366e-14
  -2.75335310e-14  1.00000000e+00 -1.47733677e-13  6.09142366e-14]
 [-1.14194368e-14  9.57963867e-14  1.00000000e+00 -1.10197565e-13
  -1.14194368e-14  9.57963867e-14  1.00000000e+00 -1.10197565e-13
  -1.14194368e-14  9.57963867e-14  1.00000000e+00 -1.10197565e-13
  -1.14194368e-14  9.57963867e-14  1.00000000e+00 -1.10197565e-13]
 [ 0.00000000e+00 -2.27373675e-13  0.00000000e+00  1.00000000e+00
   0.00000000e+00 -2.27373675e-13  0.00000000e+00  1.00000000e+00
   0.00000000e+00 -2.27373675e-13  0.00000000e

In [27]:
# Obliczenie normy 1 macierzy A
norm_A_1 = np.linalg.norm(A, ord=1)

print("Wskaźnik uwarunkowania macierzy A (norma 1):")
print(norm_A_1)

Wskaźnik uwarunkowania macierzy A (norma 1):
1.2833333333333332


oznacza to, że macierz jest względnie dobrze uwarunkowana